CREATE TABLE usuarios(
COD_USUARIO INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(80) NOT NULL,
CPF VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(14),
USER_LOGIN VARCHAR(50) NOT NULL,
USER_SENHA VARCHAR(50) NOT NULL,
DATA_CADASTRO DATE,
USER_ATIVO INT /*define se usuário está ativo no sistema*/
)

CREATE TABLE lista_compras(
COD_LISTA INT PRIMARY KEY IDENTITY(1,1),
NOME_LISTA VARCHAR(50) NOT NULL,
DATA_CRIACAO DATE NOT NULL,
COD_USUARIO INT FOREIGN KEY REFERENCES USUARIOS (COD_USUARIO),
STATUS_LISTA INT NOT NULL, /*define se a lista está aberta ou finalizada, pronta para as compras*/
LISTA_IMPORTADA INT NOT NULL, /*define se a lista foi importada e virou uma compra finalizada*/
COD_COMERCIO INT FOREIGN KEY REFERENCES COMERCIO (COD_SUP)
)

CREATE TABLE produtos_lista(
COD_ITEM INT PRIMARY KEY IDENTITY(1,1),
COD_LISTA INT FOREIGN KEY REFERENCES LISTA_COMPRAS(COD_LISTA),
COD_PRODUTO INT FOREIGN KEY REFERENCES PRODUTOS (COD_PROD),
QTD_ITEM DECIMAL(10,3),
PRECO_ITEM DECIMAL(10,2),
TOTAL_ITEM DECIMAL(10,3),
PROMOCAO INT /*define se item estava em promoção ou não*/
)


