CREATE OR ALTER PROCEDURE PR_CRIAR_LISTA_COMPRAS
@NOME_LISTA VARCHAR(50),
@COD_USUARIO INT,
@COD_COMERCIO INT
AS

INSERT INTO LISTA_COMPRAS (NOME_LISTA, DATA_CRIACAO, COD_USUARIO, STATUS_LISTA, LISTA_IMPORTADA, COD_COMERCIO)
			VALUES(@NOME_LISTA, CAST(GETDATE() AS DATE), @COD_USUARIO, 1, 0, @COD_COMERCIO)

SELECT MAX(COD_LISTA) AS COD_LISTA FROM LISTA_COMPRAS
